// import './global.less';
export {default as Page} from './page';
export {default as Loading} from './loading';
export {default as Logo} from './logo';
export {default as Menu} from './menu';
export {default as User} from './user';
export {default as Layout} from './layout';
export {default as EllipsisTooltip} from './ellipsis-tooltip';
export {default as Table} from './table';
export {default as SearchSelect} from './search-select';
// export { default as FormInput } from './forminput';
// export {default as ArrayInput} from './array-input';
export {default as InfiniteScroller} from './infinite-scroller';
export {default as Charts} from './charts';
export {default as Status} from './status';
export {default as Inputs} from './inputs';
export {default as Terminal} from './terminal';
export {default as makeDrawerForm} from './make-drawer-form';
export {default as utils} from './utils';
